import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import TopHeader from "@/components/TopHeader";
import { ScrollProvider } from "@/context/scrollContext";
// import ClientRootWrapper from "@/components/ClientRootWrapper";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata = {
    title: "Krishna Academy Dhargaon",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
        <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <ScrollProvider>

                <TopHeader />
                <Header />
                {children}
                <Footer />

        </ScrollProvider>
        </body>
        </html>
    );
}
